### ISSUE TITLE
master build not passing tests

### ISSUE THREAD

**Issue by jcrokicki** [onc-healthit/content-validator-api#7]
Hi folks,

A quick clone and build does not seem to pass the unit tests for me.
1) LOCAL_SCENARIO_DIRECTORY pointing to something other than the source tree.
2) the src/test/resources folder contains a log4j.properties file that attempts to be read and parsed which is not cool with saxon parser
3) DEFAULT_REFERENCE_FILENAME set to 170.315_b1_toc_amb_sample1_v13.pdf which is not in the master branch
1264 [main] ERROR org.sitenv.contentvalidator.service.ContentValidatorService  - Something is wrong, not able to find ref model for 170.315_b1_toc_amb_sample1_v13.pdf

I fixed 1 and 2 locally, but not sure what to do with #3 to help.

It could be all me, so any help you could provide would help.
Thanks!
- john
eClinicalWorks

**Comment by drbgfc** [comment]
I think I resolved or explained these issues via email with you. If anything is left unanswered, please let me know. It'd be great if you could summarize the answers for others here as well. Thanks.

**Comment by jcrokicki** [comment]
> I think I resolved or explained these issues via email with you. If anything is left unanswered, please let me know. It'd be great if you could summarize the answers for others here as well. Thanks.

I have seen no such email. Sorry. Can you resend? try john.rokicki at eclinicalworks dot com

**Comment by drbgfc** [comment]
I forwarded the convo/responses from last month - maybe it ended up in spam? Let me know if you get it. Thanks.

**Comment by jcrokicki** [comment]
Ah ok, found them in spam :( another thing I need to fix :) I will take a look and respond. thanks!
